name              'br_ruby'
version           '0.4.0'
description       'Adds and removes Ruby versions using ruby_build'
maintainer        'Jim Pruetting'
maintainer_email  'core-team@builtbyrobots.com'
license           'MIT License'
source_url        'https://github.com/built-by-robots/ruby-cookbook'

suggests 'apt'
suggests 'yum'

supports 'ubuntu'
supports 'debian'
supports 'centos'
supports 'redhat'
